Vagrant.configure("2") do |config|
  # we are going to be using CentOS 7 for this
  config.vm.box = "centos/7"

  # install VirtualBox guest additions
  config.vagrant.plugins = ["vagrant-vbguest"]

  # set the provider-specific options for VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.name = "l4d2-custom"
    v.customize ["modifyvm", :id, "--memory", "4096"] # Memory: 4GB
    v.customize ["modifyvm", :id, "--cpus", "4"] # Processor cores: 4
  end

  # UNCOMMENT THIS TO OPEN UP THE SERVER TO THE PUBLIC
  # create a public network on which this machine can communicate
  # config.vm.network "l4d2_public_network"

  # COMMENT THIS OUT IF YOU ARE RUNNING A PUBLIC SERVER
  # pick a static IP that doesn't conflict with anything else for the sake of consistency with LAN games
  config.vm.network "private_network", ip: "192.168.2.100"

  # forward the ports required for Steam and game operation
  # https://help.steampowered.com/en/faqs/view/2EA8-4D75-DA21-31EB
  # https://www.linode.com/docs/guides/left-4-dead-2-multiplayer-server-installation/#preparing-your-linode
  # https://serverfault.com/a/661898
  UDP_PORTS=[27015] # Dedicated or Listen Servers: gameplay traffic (UDP)
    .push(3478, 4379, 4380, 27014..27030) # Steamworks P2P Networking and Steam Voice Chat (UDP)
    .push(7777, 10999) # extra ports for SteamCMD from Linode
    .flatten
    .uniq
  UDP_PORTS.each do |port|
    config.vm.network "forwarded_port", guest: "#{port}", host: "#{port}", protocol: "udp"
  end
  TCP_PORTS=[27015] # Dedicated or Listen Servers: SRCDS Rcon port (TCP)
  TCP_PORTS.each do |port|
    config.vm.network "forwarded_port", guest: "#{port}", host: "#{port}", protocol: "tcp"
  end

  # allow SSH
  config.ssh.forward_agent = true

  # mount the /data directory in the repo at /mnt/data to allow us to use our local L4D2 add-ons
  # directory and filemodes: https://stackoverflow.com/a/19024922
  config.vm.synced_folder "../data", "/mnt/data", create: true, mount_options: ['dmode=777', 'fmode=777']

  # run the base provisioner first, then run the Left 4 Dead 2 provisioner
  config.vm.provision "shell", path: "provision/provision-base.sh"
  config.vm.provision "shell", path: "provision/provision-game-l4d2.sh"
end
